import type { LayoutNode, RuntimeDesignTokens } from '../../types/pipeline'

export function exportToJSX(
    layout: LayoutNode,
    tokens: RuntimeDesignTokens,
    componentName = 'PicoExport'
): string {
    const cssVars = tokensToCSS(tokens)

    return `// Generated by Pico\nimport React from 'react'\n\nconst tokens = ${JSON.stringify(tokens, null, 2)}\n\nexport default function ${componentName}() {\n  return (\n    <div>\n      <style>{\`\n        :root {\n${cssVars}\n        }\n      \`}</style>\n${serializeNode(layout, 3)}\n    </div>\n  )\n}`
}

function tokensToCSS(tokens: RuntimeDesignTokens): string {
    const colorVars = Object.entries(tokens.colors).map(([key, value]) => `          --color-${key}: ${value};`)
    const radiusVars = Object.entries(tokens.radius).map(([key, value]) => `          --radius-${key}: ${value};`)
    const spacingVars = Object.entries(tokens.spacing).map(([key, value]) => `          --spacing-${key}: ${value};`)
    return [...colorVars, ...radiusVars, ...spacingVars].join('\n')
}

function serializeNode(node: LayoutNode, depth = 2): string {
    const indent = '  '.repeat(depth)
    const props = node.props
        ? Object.entries(node.props)
            .map(([k, v]) => `${k}={${JSON.stringify(v)}}`)
            .join(' ')
        : ''

    const open = props ? `<${node.component} ${props}>` : `<${node.component}>`

    if (!node.children || node.children.length === 0) {
        return `${indent}${open.replace('>', ' />')}`
    }

    const children = node.children.map(child => serializeNode(child, depth + 1)).join('\n')
    return `${indent}${open}\n${children}\n${indent}</${node.component}>`
}
